framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://127.0.0.1:6379'
        pools:
            meteo.cache:
                adapter: cache.adapter.redis
                provider: 'redis://127.0.0.1:6379'
                default_lifetime: 3600  # 1 heure

